dist: Bionic
sudo: require

language: 
  - cpp
compiler: 
  - g++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gcc-10
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt install gcc-10
    - sudo apt install g++-10
    - eval "${MATRIX_EVAL}"


install:    
  - sudo apt-get remove cmake
  - CMAKE_INSTALLER=install-cmake.sh
  - curl -sSL https://github.com/Kitware/CMake/releases/download/v3.21.2/cmake-3.21.2-linux-x86_64.sh -o ${CMAKE_INSTALLER}
  - chmod +x ${CMAKE_INSTALLER}
  - sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
  - cmake --version

script:
    - sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-10 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-10
    - export CXX=/usr/bin/g++-10
    - gcc -v && g++ -v && cmake --version
    - cd ${TRAVIS_BUILD_DIR}
    - ls
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ../
    - make