dist: Bionic
sudo: require

language: 
  - cpp
compiler: 
  - g++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gcc-10
        snaps:
          - name: cmake
            confinement: classic
            channel: latest/candidate
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - whereis g++
    - whereis cmake
    - sudo rm /usr/bin/gcc
    - sudo rm /usr/bin/g++
    - sudo rm -r /usr/local/cmake-3.12.4
    - sudo rm /usr/local/cmake
    - sudo rm /usr/share/cmake
    - sudo ln -s /usr/bin/gcc-10 /usr/bin/gcc
    - sudo ln -s /usr/bin/g++-10 /usr/bin/g++
    - sudo ln -s /snap/bin/cmake /usr/bin/cmake
    - export CC=/usr/bin/gcc
    - export CXX=/usr/bin/g++
    - gcc -v && g++ -v && cmake --version
    - cd ${TRAVIS_BUILD_DIR}
    - ls
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ../
    - make
    - ./unittest